package main

import (
	"fmt"
	"math"
	"strings"
)

// RingScanResult holds one substituent probe generated by the ring SAR scan.
type RingScanResult struct {
	Pos    []Vec3  // atom positions
	Labels []string
	Bonds  []Bond
	// The ring atoms + bonds are stored separately so WriteSDF can pair them.
	RingPos    []Vec3
	RingLabels []string
	RingBonds  []Bond
	Name       string // e.g. "pos2-methyl" or "pos4-OH"
}

// ScanRings enumerates methyl and OH substituents at all 6 positions of every
// benzene/phenol ring probe in the main ProbeSet, skipping positions that would
// clash with protein.  Returns independent ProbeSet pairs (ring + substituent)
// ready for WriteSDF.
func ScanRings(ps *ProbeSet, heavy []heavyAtom) []ProbeSet {
	const (
		cCBond  = 1.54  // sp3 C–C (methyl)
		cOBond  = 1.36  // aromatic C–O (phenol)
		oCBond  = 1.43  // O–C (methoxy)
		oHBond  = 0.97  // O–H (hydroxyl, not written as atom but affects geometry)
		hardTol = 0.3
	)

	clashFree := func(pos Vec3, elem string) bool {
		r := vdw(elem)
		for _, h := range heavy {
			if pos.Sub(h.pos).Norm() < h.vdwR+r-hardTol {
				return false
			}
		}
		return true
	}

	var results []ProbeSet

	// Find all benzene ring components in ps: connected groups of 6 aromatic C
	// with exactly 6 aromatic bonds forming a 6-membered ring.
	n := len(ps.Pos)
	adj := make([][]int, n)
	for _, b := range ps.Bonds {
		i, j := b.I-1, b.J-1
		adj[i] = append(adj[i], j)
		adj[j] = append(adj[j], i)
	}

	// BFS to find connected components.
	comp := make([]int, n)
	for i := range comp {
		comp[i] = -1
	}
	nComp := 0
	for start := 0; start < n; start++ {
		if comp[start] >= 0 {
			continue
		}
		q := []int{start}
		comp[start] = nComp
		for len(q) > 0 {
			cur := q[0]
			q = q[1:]
			for _, nb := range adj[cur] {
				if comp[nb] < 0 {
					comp[nb] = nComp
					q = append(q, nb)
				}
			}
		}
		nComp++
	}

	// For each component, detect if it contains a 6-membered aromatic ring.
	for c := 0; c < nComp; c++ {
		// Collect atoms in this component.
		var cAtoms []int
		for i := 0; i < n; i++ {
			if comp[i] == c {
				cAtoms = append(cAtoms, i)
			}
		}

		// Count aromatic bonds within component.
		aromCount := 0
		for _, b := range ps.Bonds {
			if b.Order == 4 && comp[b.I-1] == c && comp[b.J-1] == c {
				aromCount++
			}
		}
		if aromCount < 6 {
			continue // not a benzene ring
		}

		// Find ring C atoms (involved in aromatic bonds).
		ringAtoms := map[int]bool{}
		for _, b := range ps.Bonds {
			if b.Order == 4 && comp[b.I-1] == c {
				ringAtoms[b.I-1] = true
				ringAtoms[b.J-1] = true
			}
		}
		if len(ringAtoms) < 6 {
			continue
		}

		// Compute ring centre and normal.
		centre := Vec3{}
		ringIdxs := []int{}
		for idx := range ringAtoms {
			if ps.Labels[idx] == "C" {
				ringIdxs = append(ringIdxs, idx)
				centre = centre.Add(ps.Pos[idx])
			}
		}
		if len(ringIdxs) < 6 {
			continue
		}
		centre = centre.Scale(1.0 / float64(len(ringIdxs)))

		// Compute plane normal from ring atoms.
		normal := ringPlaneNormal(func() []Vec3 {
			pts := make([]Vec3, len(ringIdxs))
			for i, idx := range ringIdxs {
				pts[i] = ps.Pos[idx]
			}
			return pts
		}())

		// Sort ring atoms by angle around centre for consistent 0-5 ordering.
		u := perpendicular(normal)
		v := cross3(normal, u)
		sortedRing := make([]int, len(ringIdxs))
		copy(sortedRing, ringIdxs)
		for i := 1; i < len(sortedRing); i++ {
			for j := i; j > 0; j-- {
				ai := ps.Pos[sortedRing[j]].Sub(centre)
				aj := ps.Pos[sortedRing[j-1]].Sub(centre)
				angI := math.Atan2(ai.Dot(v), ai.Dot(u))
				angJ := math.Atan2(aj.Dot(v), aj.Dot(u))
				if angI < angJ {
					sortedRing[j], sortedRing[j-1] = sortedRing[j-1], sortedRing[j]
				}
			}
		}

		// Build ring ProbeSet excluding existing cap/substituent atoms
		// (non-ring atoms bonded to ring C via single bonds).
		buildRingPS := func() ProbeSet {
			var rps ProbeSet
			remap := map[int]int{}
			// Only include atoms that are part of the aromatic ring or are O/heteroatoms.
			for _, idx := range cAtoms {
				// Include if: it's a ring atom (has aromatic bonds) OR it's a heteroatom.
				isRingAtom := false
				for _, b := range ps.Bonds {
					if b.Order == 4 && (b.I-1 == idx || b.J-1 == idx) {
						isRingAtom = true
						break
					}
				}
				isHet := false
				switch strings.ToUpper(ps.Labels[idx]) {
				case "O", "N", "S", "SE":
					isHet = true
				}
				if isRingAtom || isHet {
					remap[idx] = rps.Add(ps.Pos[idx], ps.Labels[idx])
				}
			}
			for _, b := range ps.Bonds {
				ri, rj := remap[b.I-1], remap[b.J-1]
				if ri > 0 && rj > 0 {
					rps.Bond(ri, rj, b.Order)
				}
			}
			return rps
		}

		// findRingAtom finds the 1-based index of a given position in a ProbeSet.
		findRingAtom := func(pair ProbeSet, target Vec3) int {
			for i, p := range pair.Pos {
				if p.Sub(target).Norm() < 0.01 {
					return i + 1
				}
			}
			return -1
		}

		// For each ring position 0-5, try methyl and OH/OMe substituents.
		for posIdx, ringAtomIdx := range sortedRing {
			pos := ps.Pos[ringAtomIdx]
			radial := pos.Sub(centre).unit()

			// Skip this position if the ring C already has a non-aromatic bond
			// (existing methyl cap, OH, or other substituent).
			alreadySubstituted := false
			for _, b := range ps.Bonds {
				if b.Order != 4 && ((b.I-1 == ringAtomIdx) || (b.J-1 == ringAtomIdx)) {
					alreadySubstituted = true
					break
				}
			}
			if alreadySubstituted {
				continue
			} // direction outward from ring centre

			// ── Methyl substituent ────────────────────────────────────────
			methylPos := pos.Add(radial.Scale(cCBond))
			if clashFree(methylPos, "C") {
				pair := buildRingPS()
				capIdx := -1
				for _, nb := range adj[ringAtomIdx] {
					if comp[nb] != c && ps.Labels[nb] == "C" {
						capIdx = nb
					}
				}
				if capIdx >= 0 {
					methylPos = ps.Pos[capIdx].Add(
						ps.Pos[capIdx].Sub(pos).unit().Scale(cCBond))
					if !clashFree(methylPos, "C") {
						goto skipMethyl
					}
				}
				{
					pair.Add(methylPos, "C")
					if ri := findRingAtom(pair, pos); ri > 0 {
				pair.Bond(ri, pair.Len(), 1)
			}
					pair.Name = fmt.Sprintf("pos%d-methyl", posIdx+1)
					results = append(results, pair)
				}
			skipMethyl:
			}

			// ── OH substituent ─────────────────────────────────────────────
			ohPos := pos.Add(radial.Scale(cOBond))
			if clashFree(ohPos, "O") {
				pair := buildRingPS()
				ringBase := pair.Len()
				pair.Add(ohPos, "O")
				if ri := findRingAtom(pair, pos); ri > 0 {
				pair.Bond(ri, ringBase+1, 1)
			}
				pair.Name = fmt.Sprintf("pos%d-OH", posIdx+1)
				results = append(results, pair)
			}

			// ── OMe substituent ────────────────────────────────────────────
			// The aryl ether O is sp2; C–O–C angle ≈ 120°.
			// Place methoxy C at 120° from the ring C→O bond, in the ring plane.
			// Rotating -radial (= O→ringC direction) by 120° in the ring plane:
			//   meDir = (-radial)*cos(120°) + inPlane*sin(120°)
			//         = radial*0.5 + inPlane*0.866
			// where inPlane is perpendicular to radial within the ring plane.
			oPos := pos.Add(radial.Scale(cOBond))
			inPlane := cross3(normal, radial).unit() // in-plane perp to radial
			meDir := radial.Scale(0.5).Add(inPlane.Scale(0.866))
			mePos := oPos.Add(meDir.Scale(oCBond))
			// Try both rotational directions (±inPlane) and pick the clash-free one.
			mePos2 := oPos.Add(radial.Scale(0.5).Add(inPlane.Scale(-0.866)).Scale(oCBond))
			if !clashFree(mePos, "C") && clashFree(mePos2, "C") {
				mePos = mePos2
			}
			if clashFree(oPos, "O") && clashFree(mePos, "C") {
				pair := buildRingPS()
				oIdx := pair.Add(oPos, "O")
				meIdx := pair.Add(mePos, "C")
				if ri := findRingAtom(pair, pos); ri > 0 {
					pair.Bond(ri, oIdx, 1) // ring C–O
				}
				pair.Bond(oIdx, meIdx, 1) // O–C (methoxy)
				pair.Name = fmt.Sprintf("pos%d-OMe", posIdx+1)
				results = append(results, pair)
			}
		}
	}

	return results
}
